{% set name = "pyrovelocity" %}
{% set version = "0.2.0b11" %}

# {% set gitorg = "pinellolab" %}
# {% set gittag = "v0.2.0-beta.10" %}
# {% set gitref = "beta" %}
# {% set gitrev = "9d28080c56f3678f274d6b2342b1908ac52efc3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # source archive from PyPI for release to main label
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bf038ae2caf7255866824406f8cf8b9989a40c75c609b6245b9a61c4915e8f6

  # source archive from git tag/ref/rev for testing/release to _dev label
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/refs/tags/{{ gittag }}.tar.gz
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/refs/heads/{{ gitref }}.tar.gz
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/{{ gitrev }}.tar.gz
  # sha256: 5edfd07ed970e6834c40043c94025e495a80e590bb2146f4f2cc0350abc23355

build:
  entry_points:
    - pyrovelocity=pyrovelocity.workflows.cli:main
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - pip
    - poetry-core >=1.6.0
  run:
    - python >=3.10,<3.11
    - adjusttext >=0.7.3
    - anndata >=0.10.5
    - astropy >=5.2.2
    - beartype >=0.16.4
    - click >=8.1.7
    - colorlog >=6.7.0
    - flax >=0.6.1
    - h5py >=3.8.0
    - hydra-core >=1.3.2
    - jax >=0.4.13,<=0.4.23
    - jaxlib >=0.4.12,<=0.4.23
    - jaxtyping >=0.2.25
    - leidenalg >=0.9.1
    - lightning >=2.0.0
    - mlflow >=2.10.0
    - pandas >=1.5.3
    - pyro-ppl >=1.8.6
    - pytorch >=2.0.0
    - pyyaml >=6.0.1
    - returns >=0.22.0
    - rich >=12.6.0
    - scanpy >=1.9.8
    - scipy >=1.10.1
    - scvelo >=0.3.1
    - scvi-tools >=1.1.1
    - seaborn >=0.13.2
    - termcolor >=2.2.0
    - torchmetrics >=1.2.1
    - validators >=0.22.0
    - zstandard >=0.21.0
    # workflows
    - dataclasses-json >=0.5.7
    - dulwich >=0.21.7
    - flytekit >=1.10.7
    - google-api-python-client >=2.79.0
    - hydra-core >=1.3.2
    - hydra-zen >=0.12.1
    - ipywidgets >=8.0.0
    - jupytext >=1.16.0
    - mashumaro >=3.10
    - nbconvert >=7.14.0
    - nbformat >=5.9.2
    - omegaconf >=2.3.0
    - papermill >=2.4.0
    - pyperclip >=1.8.2
    - python-dotenv >=1.0.0
    - rich-click >=1.7.3

test:
  imports:
    - pyrovelocity
  commands:
    - pytest -rA --xdoc --no-cov --disable-warnings -k "not workflows" --pyargs pyrovelocity
  requires:
    - hypothesis
    - pytest
    - pytest-cov
    - pytest-mock
    - requests-mock
    - xdoctest

about:
  home: https://github.com/pinellolab/pyrovelocity
  summary: Probabilistic modeling of RNA Velocity with pyro.
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    Pyrovelocity: A multivariate RNA Velocity model to estimate future cell
    states with uncertainty using probabilistic modeling with pyro.

    - docs: [https://pyrovelocity.readthedocs.io](https://pyrovelocity.readthedocs.io)
    - source: [https://github.com/pinellolab/pyrovelocity](https://github.com/pinellolab/pyrovelocity)

    PyPI: [https://pypi.org/project/pyrovelocity](https://pypi.org/project/pyrovelocity)

  dev_url: https://github.com/pinellolab/pyrovelocity
  doc_url: https://pyrovelocity.readthedocs.io
  doc_source_url: https://github.com/pinellolab/pyrovelocity/tree/main/docs

extra:
  recipe-maintainers:
    - cameronraysmith
    - qinqian
